export const monthly = [
  {
    name: "Basic Plan",
    price: 9.99,
    features: [
      "Up to 5 projects",
      "Unlimited tasks",
      "Basic project management features",
      "Limited integrations",
      "Email support",
    ],
    recommended: false,
    suitable: "For small teams or offices",
  },
  {
    name: "Standard Plan",
    price: 19.99,
    features: [
      "Up to 15 projects",
      "Unlimited tasks",
      "Advanced project management features",
      "More integrations",
      "Priority email support",
      "Mobile app access",
    ],
    recommended: false,
    suitable: "For medium-sized teams and departments",
  },
  {
    name: "Premium Plan",
    price: 39.99,
    features: [
      "Unlimited projects",
      "Unlimited tasks",
      "Advanced project management features",
      "Full integrations",
      "Priority email and phone support",
      "Mobile and desktop app access",
      "Team collaboration features",
      "Analytics and reporting features",
    ],
    recommended: true,
    suitable: "For large and complex organizations",
  },
];
